package view;

import model.searchDetails;
import model.singleDetails;
import model.travellers;
import controller.searchDetailsController;
import controller.singleController;
import controller.travellersController;

import java.awt.Color;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dell
 */
public class FlightDetails extends javax.swing.JFrame {
    public FlightDetails() {
        initComponents();
        getContentPane().setBackground(new Color(34,40,44));
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        jTable1.setFillsViewportHeight(true);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jButton4.setVisible(false);
        jLabel8.setVisible(false);
        jTable1.setVisible(true);
        jLabel38.setVisible(false);
        jButton1.setBackground(new Color(34,40,44));
        jButton1.setBorder(BorderFactory.createEmptyBorder());
        // try {
        //     String username = "root";
        //     String password = "0422075m";
        //     Class.forName("com.mysql.cj.jdbc.Driver");
        //     // create the connection object
        //     Connection con = DriverManager.getConnection(
        //             "jdbc:mysql://localhost:3306/FMS?characterEncoding=utf8&useSSL=false&autoReconnect=true",
        //             username, password);
        //     String query1 = "SELECT * from UpdateFlight";
        //     Statement st = con.createStatement();
        //     ResultSet rs = st.executeQuery(query1);
        //     ResultSetMetaData rsmd = rs.getMetaData();
        //     DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //     int cols = rsmd.getColumnCount();
        //     String[] colName = new String[cols];
        //     for (int i=0;i<cols;i++)
        //         colName[i]=rsmd.getColumnName(i+1);
        //     model.setColumnIdentifiers(colName);
        //     String First_Name, lName, uName, eMail, pNumber, fCost;
        //     while(rs.next()){
        //         First_Name = rs.getString(1);
        //         lName = rs.getString(2);
        //         uName = rs.getString(3);
        //         eMail = rs.getString(4);
        //         pNumber = rs.getString(5);
        //         fCost = rs.getString(6);
        //         String[] row = {First_Name, lName, uName, eMail, pNumber, fCost};
        //         model.addRow(row);
        //     }
        //     st.close();
        //     con.close();
        //     } catch (Exception e) {
        //     e.printStackTrace();
        // }

        String from0 = searchDetails.getFrom0();
        String to0 = searchDetails.getTo0();
        String ddate = searchDetails.getDdate();
        String adate = searchDetails.getAdate();
        String nationality = searchDetails.getNationality();
        System.out.println(from0);
        System.out.println(to0);
        System.out.println(ddate);
        System.out.println(adate);
        System.out.println(nationality);
        jComboBox1.setSelectedItem(from0);
        jComboBox2.setSelectedItem(to0);
        // jDateChooser1.date(ddate);
        // jDateChooser2.setDate(adate);
        try{
        String date = ddate;
        java.util.Date date2 = new SimpleDateFormat("MMM d, y").parse(date);
        jDateChooser1.setDate(date2);} catch(Exception e){
            System.out.println(e);
        }
        try{
            String date0 = adate;
            java.util.Date date1 = new SimpleDateFormat("MMM d, y").parse(date0);
            jDateChooser2.setDate(date1);} catch(Exception e){
                System.out.println(e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FlightDetails");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(30, 44, 45));

        jButton1.setBackground(new java.awt.Color(34, 40, 44));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(197, 148, 27));
        jButton1.setText("Go Airways");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 148, 27));
        jLabel1.setText("From");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 148, 27));
        jLabel2.setText("To");

        jComboBox1.setBackground(new java.awt.Color(34, 40, 44));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(197, 148, 27));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kathmandu", "Pokhara", "Dhangadhi", "Biratnagar", "Janakpur", "Surkhet", "Chitwan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(34, 40, 44));
        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(197, 148, 27));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Kathmandu", "Pokhara", "Dhangadhi", "Biratnagar", "Janakpur", "Surkhet", "Chitwan" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 148, 27));
        jLabel3.setText("Dep. Date");

        jDateChooser1.setBackground(new java.awt.Color(34, 40, 44));
        jDateChooser1.setForeground(new java.awt.Color(197, 148, 27));
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(197, 148, 27));
        jLabel4.setText("Arrival Date");

        jDateChooser2.setBackground(new java.awt.Color(34, 40, 44));
        jDateChooser2.setForeground(new java.awt.Color(197, 148, 27));
        jDateChooser2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jButton2.setBackground(new java.awt.Color(34, 40, 44));
        jButton2.setForeground(new java.awt.Color(197, 148, 27));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(197, 148, 27));
        jLabel5.setText("Traveller");

        jComboBox3.setBackground(new java.awt.Color(34, 40, 44));
        jComboBox3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(197, 148, 27));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("                                ruchan                                       ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 148, 27));
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(197, 148, 27));
        jLabel8.setText("jLabel8");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(197, 148, 27));
        jLabel38.setText("10 Flights");

        jTable1.setBackground(new java.awt.Color(34, 40, 44));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable1.setForeground(new java.awt.Color(197, 148, 27));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(34, 40, 44));
        jTable1.setRowHeight(32);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setBackground(new java.awt.Color(30, 44, 45));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(197, 148, 27));
        jLabel10.setText("Flight Number");

        jTextField2.setBackground(new java.awt.Color(30, 44, 45));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(197, 148, 27));

        jButton4.setBackground(new java.awt.Color(30, 44, 45));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(197, 148, 27));
        jButton4.setText("BOOK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(641, 641, 641)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(635, 635, 635)
                        .addComponent(jLabel38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel2)
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(25, 25, 25))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))))
                .addContainerGap(3675, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                       
 // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (evt.getSource() == jButton2){
            try{
                Date date = jDateChooser1.getDate();
                String date1 = DateFormat.getDateInstance().format(date);
                Date date0 = jDateChooser2.getDate();
                String date2 = DateFormat.getDateInstance().format(date0);
                } 
            catch(Exception e){
                        jLabel6.setVisible(true);
                        jLabel6.setText("(Please fill in the Arrival and Departure Dates)");
                }
            if(jComboBox1.getSelectedItem().toString()==jComboBox2.getSelectedItem().toString()){
                jLabel6.setVisible(true);
                jLabel6.setText("(Departure and Arrival places must be different)");
            }    
            else{
                try {
                    String username = "root";
                    String password = "0422075m";
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    // create the connection object
                    Connection con = DriverManager.getConnection(
                            "jdbc:mysql://localhost:3306/FMS?characterEncoding=utf8&useSSL=false&autoReconnect=true",
                            username, password);

                    String from = jComboBox1.getSelectedItem().toString();
                    String to = jComboBox2.getSelectedItem().toString();
                    java.util.Date date = jDateChooser1.getDate();
                    String adate = DateFormat.getDateInstance().format(date);
                    java.util.Date date2 = jDateChooser2.getDate();
                    String ddate = DateFormat.getDateInstance().format(date2);
                    System.out.println(from);
                    System.out.println(to);
                    System.out.println(adate);
                    System.out.println(ddate);
                    String query1 = "select * from UpdateFlight where from_ = '"+from+"' and destination='"+to+"';";
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery(query1);
                    ResultSetMetaData rsmd = rs.getMetaData();
                    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                    int cols = rsmd.getColumnCount();
                    System.out.println(cols);
                    String[] colName = new String[cols];
                    for (int i=0;i<cols;i++)
                        colName[i]=rsmd.getColumnName(i+1);
                    model.setColumnIdentifiers(colName);
                    String First_Name, lName, uName, eMail, pNumber, fCost;
                    while(rs.next()){
                        First_Name = rs.getString(1);
                        lName = rs.getString(2);
                        uName = rs.getString(3);
                        eMail = rs.getString(4);
                        pNumber = rs.getString(5);
                        fCost = rs.getString(6);
                        String[] row = {First_Name, lName, uName, eMail, pNumber, fCost};
                        model.addRow(row);
                    }
                    st.close();
                    con.close();
                    } catch (Exception e) {
                    e.printStackTrace();
                }
                jLabel7.setText(jComboBox1.getSelectedItem().toString());
                jLabel8.setText(jComboBox2.getSelectedItem().toString());
                jLabel6.setVisible(false);
                jLabel7.setVisible(true);
                jLabel8.setVisible(true);
                jLabel38.setVisible(true);
                jTable1.setVisible(true);
                jLabel10.setVisible(true);
                jTextField2.setVisible(true);
                jButton4.setVisible(true);
            }   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String flightNumber = jTextField2.getText();
        System.out.println(flightNumber);
        singleDetails sd = new singleDetails(flightNumber); 
        singleController singleController = new singleController();
        int insert = singleController.singleDetails(sd);  
        dispose();
        new singleFlight().setVisible(true);

        String travel = jComboBox3.getSelectedItem().toString();
        travellers travell = new travellers(travel); 
        travellersController travellersController = new travellersController();
        int insert1 = travellersController.travellers(travell); 


    }//GEN-LAST:event_jButton4ActionPerformed
    
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        dispose();
        new Home().setVisible(true);       // TODO add your handling code here:
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}