package view;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Date;
import java.text.DateFormat;

import controller.register_guiController;
import model.register_guiDetails;

/**
 *
 * @author Medini
 */
public class register_gui extends javax.swing.JFrame {

    /**
     * Creates new form register_gui
     */
    public register_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        password1 = new javax.swing.JPasswordField();
        Lname1 = new javax.swing.JTextField();
        heading = new javax.swing.JLabel();
        Fname = new javax.swing.JLabel();
        Fname1 = new javax.swing.JTextField();
        user_name1 = new javax.swing.JTextField();
        user_name = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        number = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        other = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        back = new com.k33ptoo.components.KButton();
        confirm = new com.k33ptoo.components.KButton();
        exit = new com.k33ptoo.components.KButton();
        Lname = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        confirm_password2 = new javax.swing.JPasswordField();
        confirm_password = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(50, 50, 820, 593));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });

        password1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        password1.setForeground(new java.awt.Color(197, 148, 27));
        password1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password1.setToolTipText("");
        password1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        password1.setOpaque(false);
        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });

        Lname1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Lname1.setForeground(new java.awt.Color(197, 148, 27));
        Lname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lname1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        Lname1.setCaretColor(new java.awt.Color(197, 148, 27));
        Lname1.setName("Fname"); // NOI18N
        Lname1.setOpaque(false);
        Lname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lname1ActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Lucida Handwriting", 0, 36)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 51, 153));
        heading.setText("REGISTRATION");

        Fname.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Fname.setForeground(new java.awt.Color(197, 148, 27));
        Fname.setText("First name");

        Fname1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Fname1.setForeground(new java.awt.Color(197, 148, 27));
        Fname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fname1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        Fname1.setCaretColor(new java.awt.Color(197, 148, 27));
        Fname1.setName("Fname"); // NOI18N
        Fname1.setOpaque(false);
        Fname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fname1ActionPerformed(evt);
            }
        });

        user_name1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        user_name1.setForeground(new java.awt.Color(197, 148, 27));
        user_name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user_name1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        user_name1.setCaretColor(new java.awt.Color(197, 148, 27));
        user_name1.setName("Fname"); // NOI18N
        user_name1.setOpaque(false);
        user_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_name1ActionPerformed(evt);
            }
        });

        user_name.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        user_name.setForeground(new java.awt.Color(197, 148, 27));
        user_name.setText("Username");

        email1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        email1.setForeground(new java.awt.Color(197, 148, 27));
        email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        email1.setCaretColor(new java.awt.Color(197, 148, 27));
        email1.setName("Fname"); // NOI18N
        email1.setOpaque(false);
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(197, 148, 27));
        email.setText("Email");

        number1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        number1.setForeground(new java.awt.Color(197, 148, 27));
        number1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        number1.setCaretColor(new java.awt.Color(197, 148, 27));
        number1.setName("Fname"); // NOI18N
        number1.setOpaque(false);
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        number.setForeground(new java.awt.Color(197, 148, 27));
        number.setText("Phone number");

        gender.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(197, 148, 27));
        gender.setText("Gender");

        dob.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        dob.setForeground(new java.awt.Color(197, 148, 27));
        dob.setText("Date of birth ");

        password.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(197, 148, 27));
        password.setText("Password");

        other.setForeground(new java.awt.Color(197, 148, 27));
        other.setSelected(false);
        other.setText("Other");
        other.setOpaque(false);
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        male.setForeground(new java.awt.Color(197, 148, 27));
        male.setSelected(false);
        male.setText("Male");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setForeground(new java.awt.Color(197, 148, 27));
        female.setSelected(false);
        female.setText("Female");
        female.setOpaque(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        back.setText("←");
        back.setkBorderRadius(40);
        back.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        back.setkHoverForeGround(new java.awt.Color(197, 148, 27));
        back.setkHoverStartColor(new java.awt.Color(0, 51, 102));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        confirm.setText("Confirm");
        confirm.setkBorderRadius(20);
        confirm.setkEndColor(new java.awt.Color(204, 204, 0));
        confirm.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        confirm.setkHoverForeGround(new java.awt.Color(197, 148, 27));
        confirm.setkHoverStartColor(new java.awt.Color(0, 51, 102));
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.setkBorderRadius(20);
        exit.setkHoverEndColor(new java.awt.Color(153, 153, 255));
        exit.setkHoverForeGround(new java.awt.Color(197, 148, 27));
        exit.setkHoverStartColor(new java.awt.Color(0, 51, 102));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Lname.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        Lname.setForeground(new java.awt.Color(197, 148, 27));
        Lname.setText("Last name");

        confirm_password2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        confirm_password2.setForeground(new java.awt.Color(197, 148, 27));
        confirm_password2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirm_password2.setToolTipText("");
        confirm_password2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(197, 148, 27)));
        confirm_password2.setOpaque(false);
        confirm_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_password2ActionPerformed(evt);
            }
        });

        confirm_password.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        confirm_password.setForeground(new java.awt.Color(197, 148, 27));
        confirm_password.setText("Confirm password");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(170, 170, 170)
                                                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(110, 110, 110)
                                                .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(Lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(male)
                                                                .addGap(13, 13, 13)
                                                                .addComponent(female)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(other))
                                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(confirm_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(user_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(293, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
                kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(heading)))
                                .addGap(30, 30, 30)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Fname)
                                        .addComponent(Lname))
                                .addGap(5, 5, 5)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Fname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Lname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(user_name)
                                .addGap(5, 5, 5)
                                .addComponent(user_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(email)
                                .addGap(5, 5, 5)
                                .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(number)
                                .addGap(5, 5, 5)
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(password)
                                .addGap(15, 15, 15)
                                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(confirm_password)
                                .addGap(15, 15, 15)
                                .addComponent(confirm_password2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gender)
                                .addGap(5, 5, 5)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(male)
                                        .addComponent(female)
                                        .addComponent(other))
                                .addGap(14, 14, 14)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void Lname1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void Fname1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void user_name1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(female.isSelected())
        {male.setSelected(false);}
        {other.setSelected(false);}
    }

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

    }

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(male.isSelected())
        {female.setSelected(false);}
        {other.setSelected(false);}
    }

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(other.isSelected())
        {female.setSelected(false);}
        {male.setSelected(false);}
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
    }

    private void backActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.setVisible(false);
//        new Login_frame().setVisible(true);

    }

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        register_guiController register_guiController;
        String fName = Fname1.getText();
        String lName = Lname1.getText();
        String uName = user_name1.getText();
        String eMail = email1.getText();
        String pNumber = number1.getText();
        String password = password1.getText();
        String cPassword = confirm_password2.getText();
        String gender="";
        if(male.isSelected())
        {gender="Male";}
        else if(female.isSelected())
        {gender = "Female";}
        else if(other.isSelected())
        {gender = "Others";}
        java.util.Date date = jDateChooser1.getDate();
        String date1 = DateFormat.getDateInstance().format(date);
        register_guiDetails register = new register_guiDetails(fName, lName, uName, eMail, pNumber, password, cPassword, gender, date1);
        register_guiController = new register_guiController();
        int insert = register_guiController.register_guiDetails(register);
        System.out.println(fName);
        System.out.println(lName);
        System.out.println(uName);
        System.out.println(eMail);
        System.out.println(pNumber);
        System.out.println(password);
        System.out.println(cPassword);
        System.out.println(gender);
        System.out.println(date1);
    }

    private void confirm_password2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String gender3="";
        if(male.isSelected())
        {gender3="Male";}
        else if(female.isSelected())
        {gender3 = "Female";}
        else if(other.isSelected())
        {gender3 = "Others";}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel Fname;
    private javax.swing.JTextField Fname1;
    private javax.swing.JLabel Lname;
    private javax.swing.JTextField Lname1;
    private com.k33ptoo.components.KButton back;
    private com.k33ptoo.components.KButton confirm;
    private javax.swing.JLabel confirm_password;
    private javax.swing.JPasswordField confirm_password2;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel email;
    private javax.swing.JTextField email1;
    private com.k33ptoo.components.KButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel heading;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel number;
    private javax.swing.JTextField number1;
    private javax.swing.JRadioButton other;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JLabel user_name;
    private javax.swing.JTextField user_name1;
    // End of variables declaration
}